export const HESLA_DANE = [
  {
    slug: 'prijem-podle-paragrafu-9',
    pojem: 'Příjem podle § 9',
    oblast: 'dane',
    definice: 'Příjem z nájmu nemovitostí u fyzické osoby; nepodléhá sociálnímu ani zdravotnímu pojištění a nevyžaduje živnostenské oprávnění.',
    vysvetleni: [
      'Takhle se daní běžný dlouhodobý pronájem bytu. Daní se to, co ti v daném roce skutečně došlo — předepsané, ale nezaplacené nájemné se nedaní.',
      'Hranice se posune ve chvíli, kdy k bydlení přidáš služby jako úklid, výměnu prádla nebo předávání klíčů hostům. Pak jde o ubytovací službu podle § 7 se vším všudy, včetně pojistného a živnosti.',
    ],
    zdroj: '§ 9 zákona o daních z příjmů',
    souvisejici: ['vydajovy-pausal', 'skutecne-vydaje', 'ubytovaci-sluzba'],
    clanek: 'dane-z-pronajmu',
    kalkulacka: 'dan-z-pronajmu',
  },
  {
    slug: 'vydajovy-pausal',
    pojem: 'Výdajový paušál 30 %',
    oblast: 'dane',
    definice: 'Možnost odečíst od příjmů z nájmu 30 % bez dokládání, nejvýše však 600 000 Kč za rok.',
    vysvetleni: [
      'Strop se naplno využije u ročního příjmu 2 miliony Kč; nad tuhle hranici už paušální výdaje dál nerostou.',
      'U paušálu nic nedokládáš a vedeš jen evidenci příjmů. Výši příjmů ale musíš umět prokázat — typicky výpisem z účtu.',
    ],
    pozor: 'Paušál nezohledňuje odpis ani úroky z hypotéky. U bytu s hypotékou proto obvykle prohrává se skutečnými výdaji, a to o desítky tisíc ročně.',
    zdroj: '§ 9 odst. 4 zákona o daních z příjmů',
    souvisejici: ['skutecne-vydaje', 'prijem-podle-paragrafu-9', 'odpis'],
    clanek: 'dane-z-pronajmu',
    kalkulacka: 'dan-z-pronajmu',
  },
  {
    slug: 'skutecne-vydaje',
    pojem: 'Skutečné výdaje',
    oblast: 'dane',
    definice: 'Doložitelné náklady na pronajímanou nemovitost, které se odečtou od příjmů místo paušálu.',
    vysvetleni: [
      'Patří sem odpis nemovitosti, úroky z hypotéky na její pořízení, opravy a údržba, pojištění, daň z nemovitých věcí, odměna správci, inzerce a poplatky bance.',
      'Způsob se volí pro celé zdaňovací období. Přejít mezi lety lze, ale přechod má daňové dopady — vyplatí se ho spočítat dopředu.',
    ],
    pozor: 'Jistota není příjem a splátka jistiny hypotéky není výdaj. Výdajem jsou jen úroky.',
    zdroj: '§ 9 odst. 3 zákona o daních z příjmů',
    souvisejici: ['vydajovy-pausal', 'odpis', 'technicke-zhodnoceni'],
    clanek: 'dane-z-pronajmu',
    kalkulacka: 'dan-z-pronajmu',
  },
  {
    slug: 'odpis',
    pojem: 'Odpis nemovitosti',
    oblast: 'dane',
    definice: 'Postupné promítnutí pořizovací ceny nemovitosti do výdajů; byty a budovy se odepisují 30 let.',
    vysvetleni: [
      'Rovnoměrně je to 1,4 % vstupní ceny v prvním roce a 3,4 % v dalších. Zrychleně se v prvním roce dělí vstupní cena koeficientem 30 a v dalších letech se počítá z dvojnásobku zůstatkové ceny.',
      'Vstupní cenou je pořizovací cena bez hodnoty pozemku — ten se neodepisuje. U rodinného domu je proto nutné cenu rozdělit.',
    ],
    pozor: 'Pokud jsi nemovitost pořídil výrazně dřív, než jsi ji začal pronajímat, platí pro určení vstupní ceny zvláštní pravidla. Špatně určená cena se táhne třicet let.',
    zdroj: '§ 30 až § 32 zákona o daních z příjmů',
    souvisejici: ['skutecne-vydaje', 'technicke-zhodnoceni', 'vydajovy-pausal'],
    clanek: 'dane-z-pronajmu',
    kalkulacka: 'odpisy-nemovitosti',
  },
  {
    slug: 'technicke-zhodnoceni',
    pojem: 'Technické zhodnocení',
    oblast: 'dane',
    definice: 'Nástavba, přístavba, rekonstrukce nebo modernizace nad 80 000 Kč za rok; nedává se do výdajů najednou, ale zvyšuje vstupní cenu.',
    vysvetleni: [
      'Rozdíl proti opravě je zásadní. Oprava vrací věc do původního stavu a je výdajem hned. Technické zhodnocení mění účel nebo parametry a odepisuje se.',
      'Výměna prasklého umyvadla za stejné je oprava. Nová kuchyňská linka, zateplení nebo přestavba koupelny jsou technické zhodnocení.',
    ],
    zdroj: '§ 33 zákona o daních z příjmů',
    souvisejici: ['odpis', 'skutecne-vydaje'],
    clanek: 'dane-z-pronajmu',
  },
  {
    slug: 'danove-priznani',
    pojem: 'Daňové přiznání z nájmu',
    oblast: 'dane',
    definice: 'Přiznání podává zaměstnanec s příjmy z nájmu nad 20 000 Kč ročně, ostatní při celkovém příjmu nad 50 000 Kč.',
    vysvetleni: [
      'Lhůta je tři měsíce po konci roku, elektronicky čtyři a s daňovým poradcem šest. Když termín padne na víkend nebo svátek, posouvá se na nejbližší pracovní den.',
      'Sazba daně je 15 % pro část základu do 36násobku průměrné mzdy a 23 % nad touto hranicí.',
    ],
    pozor: 'Zaměstnavatel neudělá roční zúčtování tomu, kdo má vedle zaměstnání příjmy z nájmu nad hranici. Přiznání je pak povinné.',
    zdroj: '§ 38g zákona o daních z příjmů, § 136 daňového řádu',
    souvisejici: ['prijem-podle-paragrafu-9', 'vydajovy-pausal'],
    clanek: 'dane-z-pronajmu',
    kalkulacka: 'dan-z-pronajmu',
  },
  {
    slug: 'dan-z-nemovitych-veci',
    pojem: 'Daň z nemovitých věcí',
    oblast: 'dane',
    definice: 'Místní majetková daň, kterou platí vlastník nemovitosti podle stavu k 1. lednu; u pronájmu je daňově uznatelným výdajem.',
    vysvetleni: [
      'Přiznání se podává jen při změně — po koupi, prodeji nebo stavební úpravě, a to do konce ledna následujícího roku. V dalších letech chodí složenka nebo platba podle dřívějšího přiznání.',
      'Výše se liší obec od obce podle místního koeficientu, takže dva stejné byty v různých městech můžou mít výrazně jinou daň.',
    ],
    zdroj: 'zákon č. 338/1992 Sb.',
    souvisejici: ['skutecne-vydaje', 'danove-priznani'],
    clanek: 'dane-z-pronajmu',
  },
  {
    slug: 'ubytovaci-sluzba',
    pojem: 'Ubytovací služba',
    oblast: 'dane',
    definice: 'Přechodné ubytování se službami — typicky krátkodobý pronájem přes platformy; daní se podle § 7 a vyžaduje živnost.',
    vysvetleni: [
      'Rozhoduje účel a to, co kolem bydlení poskytuješ. Nájem je o uspokojení bytové potřeby, ubytovací služba o přechodném ubytování s úklidem, prádlem a předáváním klíčů.',
      'Na rozdíl od nájmu se z ní platí sociální i zdravotní pojištění, vede se evidenční kniha hostů a cizinci se hlásí cizinecké policii.',
    ],
    pozor: 'Provize od zahraniční platformy z tebe udělá identifikovanou osobu k DPH, i když plátcem nejsi. Na tohle se nejčastěji zapomíná a doměřuje se zpětně.',
    zdroj: '§ 7 zákona o daních z příjmů',
    souvisejici: ['prijem-podle-paragrafu-9', 'poplatek-z-pobytu'],
    clanek: 'kratkodoby-pronajem',
  },
  {
    slug: 'poplatek-z-pobytu',
    pojem: 'Poplatek z pobytu',
    oblast: 'dane',
    definice: 'Místní poplatek, který platí host za každý započatý den pobytu kromě dne příjezdu; horní hranice sazby je 50 Kč.',
    vysvetleni: [
      'Konkrétní sazbu i osvobození určuje obec vyhláškou, takže se liší město od města. Ubytovatel poplatek jen vybírá a odvádí obci.',
      'Poplatek není tvůj příjem a do daňového přiznání nepatří. Vede se k němu evidenční kniha podle obecní vyhlášky.',
    ],
    zdroj: 'zákon č. 565/1990 Sb., o místních poplatcích',
    souvisejici: ['ubytovaci-sluzba'],
    clanek: 'kratkodoby-pronajem',
  },
  {
    slug: 'identifikovana-osoba',
    pojem: 'Identifikovaná osoba',
    oblast: 'dane',
    definice: 'Kdo není plátcem DPH, ale přijal službu od osoby povinné k dani ze zahraničí a musí z ní odvést daň.',
    vysvetleni: [
      'U krátkodobého pronájmu se jí člověk stane prakticky hned — stačí přijmout provizi od Airbnb nebo Booking.com.',
      'Identifikovaná osoba z vlastního ubytování DPH neodvádí a nemá nárok na odpočet. Musí se ale registrovat a z přijatých zahraničních služeb daň přiznat a zaplatit.',
    ],
    zdroj: 'zákon č. 235/2004 Sb., o dani z přidané hodnoty',
    souvisejici: ['ubytovaci-sluzba', 'poplatek-z-pobytu'],
    clanek: 'kratkodoby-pronajem',
  },
]
