export const HESLA_PENIZE = [
  {
    slug: 'najemne',
    pojem: 'Nájemné',
    oblast: 'penize',
    definice: 'Platba za užívání bytu samotného, bez záloh na služby; její výši si strany sjednají ve smlouvě.',
    vysvetleni: [
      'Nájemné a zálohy na služby jsou dvě různé věci a patří do smlouvy odděleně. Nájemné je příjem pronajímatele a daní se; zálohy na služby jen vybíráš, platíš z nich dodavatelům a na konci období vyúčtuješ.',
      'Nájemné se platí předem na měsíc dopředu, není-li ujednáno jinak, a splatné je do pátého dne příslušného platebního období.',
    ],
    pozor: 'Smíchat nájemné a zálohy do jedné částky znamená, že nemáš z čeho udělat vyúčtování a nájemce má právo se ptát, kolik z toho šlo na teplo.',
    zdroj: '§ 2246 a § 2251 občanského zákoníku',
    souvisejici: ['zalohy-na-sluzby', 'predpis-plateb', 'zvyseni-najemneho'],
    clanek: 'najemni-smlouva',
  },
  {
    slug: 'zvyseni-najemneho',
    pojem: 'Zvýšení nájemného',
    oblast: 'penize',
    definice: 'Jednostranně lze nájemné zvýšit jen písemným návrhem, nejvýše o 20 % za poslední tři roky a do výše srovnatelného nájemného v místě.',
    vysvetleni: [
      'Nájemce má dva měsíce na písemné vyjádření. Souhlasí-li, platí nové nájemné počínaje třetím kalendářním měsícem po dojití návrhu. Mlčení se bere jako nesouhlas.',
      'Když nájemce nesouhlasí, má pronajímatel další tři měsíce na to, aby navrhl soudu určení výše nájemného. K návrhu podanému dřív než rok od posledního zvýšení se nepřihlíží.',
      'Má-li smlouva inflační doložku, postupuje se podle ní a zákonný postup se nepoužije — ani strop dvaceti procent.',
    ],
    zdroj: '§ 2249 občanského zákoníku, nařízení vlády č. 453/2013 Sb.',
    souvisejici: ['inflacni-dolozka', 'srovnatelne-najemne', 'najemne'],
    clanek: 'zvyseni-najmu',
  },
  {
    slug: 'inflacni-dolozka',
    pojem: 'Inflační doložka',
    oblast: 'penize',
    definice: 'Ujednání ve smlouvě, podle kterého se nájemné každoročně upraví o míru inflace; nahrazuje zákonný postup zvyšování.',
    vysvetleni: [
      'Dobře napsaná doložka vždy pojmenuje čtyři věci: podle jakého indexu se zvyšuje (nejčastěji index spotřebitelských cen ČSÚ), za jaké období se index bere, od kdy nová částka platí a jak se nájemci oznámí.',
      'Protože se postupuje podle smlouvy, neplatí strop dvaceti procent za tři roky ani lhůty podle § 2249. Pro pronajímatele je to proto výhodnější cesta.',
    ],
    pozor: 'Doložka, která říká jen „nájemné se každoročně zvýší o inflaci", bývá zdrojem sporu. Nejasné ujednání se vykládá spíš ve prospěch nájemce jako slabší strany.',
    souvisejici: ['zvyseni-najemneho', 'najemne'],
    clanek: 'zvyseni-najmu',
  },
  {
    slug: 'srovnatelne-najemne',
    pojem: 'Srovnatelné nájemné',
    oblast: 'penize',
    definice: 'Nájemné obvyklé v daném místě a čase u bytů srovnatelné velikosti, stavu a polohy; strop pro zákonné zvýšení.',
    vysvetleni: [
      'Hledisko srovnatelnosti popisuje nařízení vlády č. 453/2013 Sb. V praxi stačí k návrhu na zvýšení přiložit tři aktuální nabídky srovnatelných bytů ve stejné lokalitě.',
      'K návrhu, který výši nájemného neobsahuje nebo nedokládá splnění podmínek, se nepřihlíží — nespustí tedy vůbec žádnou lhůtu.',
    ],
    zdroj: 'nařízení vlády č. 453/2013 Sb.',
    souvisejici: ['zvyseni-najemneho', 'najemne'],
    clanek: 'zvyseni-najmu',
  },
  {
    slug: 'zalohy-na-sluzby',
    pojem: 'Zálohy na služby',
    oblast: 'penize',
    definice: 'Měsíční platby na teplo, vodu a další služby, které se po skončení zúčtovacího období vyúčtují proti skutečným nákladům.',
    vysvetleni: [
      'Zálohy nejsou příjmem pronajímatele, pokud je jen vybírá, platí z nich dodavatelům a na konci roku vyúčtuje. Do daňového přiznání proto nepatří.',
      'Výši záloh lze během roku změnit při změně ceny služby, rozsahu spotřeby nebo počtu osob v bytě. Změnu stačí písemně oznámit a odůvodnit — typicky posledním vyúčtováním.',
    ],
    zdroj: 'zákon č. 67/2013 Sb.',
    souvisejici: ['vyuctovani-sluzeb', 'evidencni-list', 'zuctovaci-obdobi'],
    clanek: 'vyuctovani-sluzeb',
    kalkulacka: 'vyuctovani-sluzeb',
  },
  {
    slug: 'evidencni-list',
    pojem: 'Evidenční list',
    oblast: 'penize',
    definice: 'Příloha nájemní smlouvy s rozpisem nájemného a jednotlivých záloh; dá se měnit bez dodatku, pokud na ni smlouva odkazuje.',
    vysvetleni: [
      'Evidenční list dnes nemá oporu v zákoně — pochází z dob regulovaného nájemného. Přesto se používá dál, protože je to jediná příloha, kterou lze změnit jednostranným oznámením.',
      'Patří do něj označení bytu, počet osob, nájemné samostatně, zálohy rozepsané po jednotlivých službách, celková měsíční platba a datum účinnosti.',
    ],
    pozor: 'Funguje to jen tehdy, když smlouva výslovně říká, že se výše záloh stanovuje evidenčním listem a že ji pronajímatel může změnit písemným oznámením. Bez té věty je nový list jen papír.',
    souvisejici: ['zalohy-na-sluzby', 'predpis-plateb', 'najemni-smlouva'],
    clanek: 'evidencni-list',
  },
  {
    slug: 'predpis-plateb',
    pojem: 'Předpis plateb',
    oblast: 'penize',
    definice: 'Částka, kterou má nájemce za daný měsíc zaplatit — nájemné plus zálohy na služby.',
    vysvetleni: [
      'Předpis vychází ze smlouvy, případně z evidenčního listu. Proti němu se porovnává to, co doopravdy přišlo na účet; rozdíl je nedoplatek nebo přeplatek za daný měsíc.',
      'Po výměně nájemce se předpis mění od data nové smlouvy, ne od začátku roku. Starší měsíce zůstávají na původní částce.',
    ],
    pozor: 'Daní se to, co opravdu přišlo, ne co bylo předepsáno. Nezaplacené nájemné se nedaní.',
    souvisejici: ['najemne', 'zalohy-na-sluzby', 'neplatic'],
    clanek: 'zvyseni-najmu',
  },
  {
    slug: 'neplatic',
    pojem: 'Dluh na nájemném',
    oblast: 'penize',
    definice: 'Nezaplacené nájemné a zálohy; při dluhu ve výši tří měsíčních plateb jde o zvlášť závažné porušení povinností nájemce.',
    vysvetleni: [
      'Postup má pořadí: upomínka hned první týden, písemná výzva s rozpisem dluhu a lhůtou v druhém měsíci, teprve pak výpověď. Všechno písemně a s doložením doručení.',
      'Z jistoty se dluh zpravidla započítává až při skončení nájmu. Použít ji dřív jde jen tehdy, když to smlouva umožňuje včetně povinnosti nájemce jistotu doplnit.',
    ],
    pozor: 'Výměna zámku, odpojení vody nebo vystěhování věcí je nedovolená svépomoc — z poškozeného se tím stává ten, kdo porušuje právo.',
    zdroj: '§ 2291 občanského zákoníku',
    souvisejici: ['vypoved-bez-vypovedni-doby', 'jistota', 'predpis-plateb'],
    clanek: 'neplatici-najemnik',
  },
  {
    slug: 'urok-z-prodleni',
    pojem: 'Úrok z prodlení',
    oblast: 'penize',
    definice: 'Zákonný úrok z dlužné částky; jeho sazba je repo sazba ČNB platná pro první den kalendářního pololetí zvýšená o 8 procentních bodů.',
    vysvetleni: [
      'Uplatní se u nezaplaceného nájemného i u nevráceného přeplatku z vyúčtování. Nárok vzniká ze zákona, i když o něm smlouva mlčí.',
      'Ze stejné sazby se v praxi vychází u úroků z jistoty, protože zákon u ní mluví jen o „zákonné sazbě", aniž by ji přesně určil. Výklad ale není ustálený.',
    ],
    zdroj: 'nařízení vlády č. 351/2013 Sb.',
    souvisejici: ['jistota', 'neplatic'],
    kalkulacka: 'urok-z-kauce',
  },
  {
    slug: 'preplatek-nedoplatek',
    pojem: 'Přeplatek a nedoplatek',
    oblast: 'penize',
    definice: 'Rozdíl mezi zaplacenými zálohami a skutečnými náklady na služby za zúčtovací období.',
    vysvetleni: [
      'Kladný rozdíl je přeplatek, který se vrací nájemci; záporný je nedoplatek, který nájemce doplatí. Vypořádat se musí do čtyř měsíců od doručení vyúčtování, není-li ujednáno jinak.',
      'Nedoplatek je dluh jako každý jiný: lze ho započíst proti jistotě a vymáhat. Dluh na službách se navíc počítá do posuzování, zda nájemce porušuje povinnosti zvlášť závažným způsobem.',
    ],
    zdroj: 'zákon č. 67/2013 Sb., § 7',
    souvisejici: ['vyuctovani-sluzeb', 'zalohy-na-sluzby', 'neplatic'],
    clanek: 'vyuctovani-sluzeb',
    kalkulacka: 'vyuctovani-sluzeb',
  },
]
