export const HESLA_SMLOUVA = [
  {
    slug: 'najemni-smlouva',
    pojem: 'Nájemní smlouva',
    oblast: 'smlouva',
    definice: 'Písemná dohoda, kterou pronajímatel přenechává nájemci byt k zajištění bytových potřeb a nájemce se zavazuje platit nájemné.',
    vysvetleni: [
      'U nájmu bytu zákon vyžaduje písemnou formu. Ze smlouvy musí být zřejmé, kdo je pronajímatel a kdo nájemce, který byt se pronajímá, za kolik a na jak dlouho. Zálohy na služby se uvádějí odděleně od nájemného — potřebuješ to u vyúčtování i u daní.',
      'Chybí-li ve smlouvě doba nájmu, platí nájem na dobu neurčitou. Pokud smlouva písemná není, ale nájemce byt v dobré víře užívá alespoň tři roky, nemůže pronajímatel neplatnost pro nedostatek formy namítat.',
    ],
    pozor: 'Nájemce se předem nemůže vzdát práv, která mu dává zákon. K ujednáním typu zákazu trvalého pobytu nebo výpovědních důvodů nad rámec zákona se nepřihlíží, i když je podepíše.',
    zdroj: '§ 2235 a násl. občanského zákoníku',
    souvisejici: ['jistota', 'evidencni-list', 'predavaci-protokol'],
    clanek: 'najemni-smlouva',
  },
  {
    slug: 'jistota',
    pojem: 'Jistota (kauce)',
    oblast: 'smlouva',
    definice: 'Peníze složené nájemcem při podpisu smlouvy, ze kterých pronajímatel na konci nájmu uhradí dluhy a škodu nad rámec běžného opotřebení.',
    vysvetleni: [
      'Jistota spolu s případnou smluvní pokutou nesmí v souhrnu přesáhnout trojnásobek měsíčního nájemného. Počítá se nájemné samotné, ne nájemné plus zálohy na služby.',
      'Nájemce má ze zákona právo na úroky z jistoty od jejího poskytnutí, nejméně ve výši zákonné sazby. Nárok vzniká i tehdy, když o něm smlouva mlčí, a nelze ho vyloučit.',
      'Při skončení nájmu se jistota vrací snížená o to, co nájemce po právu dluží. Každý odpočet musí pronajímatel umět doložit — fakturou, fotografií nebo odečtem měřidel.',
    ],
    pozor: 'Bez předávacího protokolu se těžko prokazuje, že škoda vznikla za nájemce. Bez něj většinou nelze strhnout skoro nic.',
    zdroj: '§ 2254 občanského zákoníku',
    souvisejici: ['smluvni-pokuta', 'predavaci-protokol', 'bezne-opotrebeni'],
    clanek: 'jistota-kauce',
    kalkulacka: 'urok-z-kauce',
  },
  {
    slug: 'smluvni-pokuta',
    pojem: 'Smluvní pokuta',
    oblast: 'smlouva',
    definice: 'Částka sjednaná ve smlouvě pro případ porušení povinnosti nájemce; spolu s jistotou nesmí přesáhnout trojnásobek měsíčního nájemného.',
    vysvetleni: [
      'Možnost sjednat u nájmu bytu smluvní pokutu se do zákona vrátila novelou účinnou od 1. července 2020 — právě se společným stropem s jistotou.',
      'Když si tedy vezmeš jistotu v plné výši tří nájmů, na smluvní pokutu už prostor nezbývá. U nájemného 20 000 Kč a jistoty 50 000 Kč zbývá na pokuty 10 000 Kč.',
    ],
    zdroj: '§ 2254 občanského zákoníku, novela č. 163/2020 Sb.',
    souvisejici: ['jistota', 'najemni-smlouva'],
    clanek: 'jistota-kauce',
  },
  {
    slug: 'doba-urcita',
    pojem: 'Nájem na dobu určitou',
    oblast: 'smlouva',
    definice: 'Nájem sjednaný do konkrétního data; skončí uplynutím doby, ale mlčením pronajímatele se může automaticky prodloužit.',
    vysvetleni: [
      'Pokud nájemce užívá byt dál alespoň tři měsíce po dni, kdy měl nájem skončit, a pronajímatel ho písemně nevyzve, aby byt opustil, nájem se obnovuje na stejnou dobu — nejvýše však na dva roky.',
      'Smlouva na dobu určitou není ochrana proti špatnému nájemci: během sjednané doby ji taky nelze jen tak vypovědět. Výhodou je jen to, že jednou skončí sama.',
    ],
    pozor: 'Na automatické prodloužení se nejčastěji zapomíná. Vyplatí se hlídat si konec nájmu aspoň měsíc dopředu.',
    zdroj: '§ 2285 občanského zákoníku',
    souvisejici: ['doba-neurcita', 'vypovedni-doba', 'najemni-smlouva'],
    clanek: 'najemni-smlouva',
  },
  {
    slug: 'doba-neurcita',
    pojem: 'Nájem na dobu neurčitou',
    oblast: 'smlouva',
    definice: 'Nájem bez sjednaného konce; nájemce ho může vypovědět bez důvodu, pronajímatel jen ze zákonného důvodu.',
    vysvetleni: [
      'Výpovědní doba je u obou stran tři měsíce a běží od prvního dne kalendářního měsíce následujícího po měsíci, v němž výpověď došla druhé straně.',
      'Pronajímatel může u nájmu na dobu neurčitou navíc vypovědět, když byt potřebuje pro sebe, pro manžela po rozvodu nebo pro příbuzného v řadě přímé či sourozence. Byt pak musí k uvedenému účelu skutečně použít.',
    ],
    zdroj: '§ 2287 a § 2288 občanského zákoníku',
    souvisejici: ['doba-urcita', 'vypovedni-doba', 'vypoved-bez-vypovedni-doby'],
    clanek: 'vypoved-z-najmu',
  },
  {
    slug: 'vypovedni-doba',
    pojem: 'Výpovědní doba',
    oblast: 'smlouva',
    definice: 'Tři měsíce, po které nájem po doručení výpovědi ještě trvá; běží od prvního dne měsíce následujícího po doručení.',
    vysvetleni: [
      'Výpověď doručená 20. května tedy znamená, že nájem skončí 31. srpna. Rozhoduje dojití výpovědi, ne její odeslání ani převzetí — zásilka doručená na adresu bytu se zpravidla považuje za došlou, i když si ji adresát nevyzvedne.',
      'Výpověď od pronajímatele musí obsahovat konkrétní důvod popsaný skutkově a poučení o právu podat námitky a navrhnout soudu přezkoumání. Bez poučení je neplatná.',
    ],
    pozor: 'Chybějící poučení je nejčastější důvod, proč výpovědi u soudu padají — i když nájemce skutečně neplatí.',
    zdroj: '§ 2286 občanského zákoníku',
    souvisejici: ['vypoved-bez-vypovedni-doby', 'doba-neurcita'],
    clanek: 'vypoved-z-najmu',
  },
  {
    slug: 'vypoved-bez-vypovedni-doby',
    pojem: 'Výpověď bez výpovědní doby',
    oblast: 'smlouva',
    definice: 'Okamžité ukončení nájmu, když nájemce porušuje své povinnosti zvlášť závažným způsobem — typicky dluží nájemné a služby za tři měsíce.',
    vysvetleni: [
      'Zákon sám jmenuje nezaplacení nájemného a nákladů na služby za dobu alespoň tří měsíců, poškozování bytu nebo domu závažným či nenapravitelným způsobem, způsobování závažných škod a obtíží a neoprávněné užívání bytu k jinému účelu.',
      'Dluh nemusí být za tři měsíce po sobě — rozhoduje jeho celková výše odpovídající třem měsíčním platbám.',
    ],
    pozor: 'Nejdřív musí přijít prokazatelná výzva, aby nájemce protiprávní stav odstranil. Bez ní soud výpověď zpravidla zruší, i když dluh existuje.',
    zdroj: '§ 2291 občanského zákoníku',
    souvisejici: ['vypovedni-doba', 'neplatic'],
    clanek: 'neplatici-najemnik',
  },
  {
    slug: 'podnajem',
    pojem: 'Podnájem',
    oblast: 'smlouva',
    definice: 'Přenechání bytu nebo jeho části další osobě samotným nájemcem, ne vlastníkem.',
    vysvetleni: [
      'Pokud nájemce v bytě sám bydlí, může jeho část podnajmout i bez souhlasu pronajímatele. Chce-li podnajmout byt celý nebo v něm nebydlí, souhlas pronajímatele potřebuje — a to písemný.',
      'Podnájem je vždy odvozený od nájmu: skončí-li nájem, skončí automaticky i podnájem. Podnájemník nemá vůči vlastníkovi přímý vztah.',
    ],
    pozor: 'Podnájem bez souhlasu tam, kde je potřeba, je hrubé porušení povinností nájemce a může být výpovědním důvodem.',
    zdroj: '§ 2274 a násl. občanského zákoníku',
    souvisejici: ['najemni-smlouva', 'vypovedni-doba'],
  },
  {
    slug: 'predavaci-protokol',
    pojem: 'Předávací protokol',
    oblast: 'smlouva',
    definice: 'Zápis o stavu bytu, měřidel a klíčů při předání; není povinný, ale rozhoduje většinu sporů o kauci.',
    vysvetleni: [
      'Patří do něj datum předání, stavy všech měřidel včetně výrobních čísel, počet předaných klíčů, soupis vybavení a popis už existujících závad. Přílohou bývají fotografie.',
      'Stejný protokol se dělá i při vracení bytu. Bez obou se po letech těžko dokazuje, co v bytě bylo a co vzniklo za nájemce.',
    ],
    zdroj: 'praxe; zákon ho nevyžaduje',
    souvisejici: ['jistota', 'bezne-opotrebeni', 'odecet-meridel'],
    clanek: 'predavaci-protokol',
  },
  {
    slug: 'bezne-opotrebeni',
    pojem: 'Běžné opotřebení',
    oblast: 'smlouva',
    definice: 'Přirozené opotřebení bytu užíváním, které nese pronajímatel a nelze ho strhnout z jistoty.',
    vysvetleni: [
      'Zašlá malba po letech bydlení, opotřebená podlaha v průchozí části nebo vysloužilé těsnění jsou běžné opotřebení. Díry po desítkách hmoždinek, propálená pracovní deska nebo prasklé umyvadlo už ne.',
      'Běžnou údržbu a drobné opravy hradí nájemce ze zákona i bez ujednání. Co přesně to je, vymezuje nařízení vlády č. 308/2015 Sb. — ve smlouvě se na něj vyplatí odkázat.',
    ],
    zdroj: 'nařízení vlády č. 308/2015 Sb.',
    souvisejici: ['jistota', 'predavaci-protokol'],
    clanek: 'jistota-kauce',
  },
]
