export const HESLA_SLUZBY = [
  {
    slug: 'zuctovaci-obdobi',
    pojem: 'Zúčtovací období',
    oblast: 'sluzby',
    definice: 'Období, za které se vyúčtovávají služby — nejčastěji kalendářní rok, nejvýše dvanáct měsíců.',
    vysvetleni: [
      'Od jeho konce běží všechny lhůty: vyúčtování musí být doručeno do čtyř měsíců a peníze vypořádané do čtyř měsíců od doručení.',
      'U kalendářního roku to znamená, že vyúčtování za rok musí být u nájemce nejpozději do konce dubna následujícího roku.',
    ],
    zdroj: 'zákon č. 67/2013 Sb.',
    souvisejici: ['vyuctovani-sluzeb', 'zalohy-na-sluzby'],
    clanek: 'vyuctovani-sluzeb',
    kalkulacka: 'vyuctovani-sluzeb',
  },
  {
    slug: 'vyuctovani-sluzeb',
    pojem: 'Vyúčtování služeb',
    oblast: 'sluzby',
    definice: 'Rozpis skutečných nákladů na služby proti zaplaceným zálohám, který musí pronajímatel doručit do čtyř měsíců od konce zúčtovacího období.',
    vysvetleni: [
      'Musí obsahovat označení bytu a období, u každé služby skutečnou výši nákladu a způsob rozúčtování, spotřebu podle měřidel, součet zaplacených záloh a výsledný přeplatek či nedoplatek s termínem vypořádání.',
      'Nájemce má 30 dnů od doručení na námitky i na písemnou žádost o doložení podkladů; pronajímatel má na obojí 30 dnů. Nepodá-li nájemce námitky včas, platí, že s vyúčtováním souhlasí.',
    ],
    pozor: 'Za nedoručení včas nebo nedoložení podkladů vzniká nárok na pokutu 50 Kč za každý započatý den prodlení, ledaže je ve smlouvě ujednána jiná výše.',
    zdroj: 'zákon č. 67/2013 Sb., § 7, § 8 a § 13',
    souvisejici: ['zuctovaci-obdobi', 'rozuctovani', 'preplatek-nedoplatek'],
    clanek: 'vyuctovani-sluzeb',
    kalkulacka: 'vyuctovani-sluzeb',
  },
  {
    slug: 'rozuctovani',
    pojem: 'Rozúčtování nákladů',
    oblast: 'sluzby',
    definice: 'Rozdělení celkového nákladu na službu mezi jednotlivé byty — podle měřidel, počtu osob nebo podlahové plochy.',
    vysvetleni: [
      'Co se měří, rozúčtuje se podle měřidel. Co se neměří, podle klíče ujednaného ve smlouvě — nejčastěji počtu osob nebo podlahové plochy.',
      'U tepla a společně připravované teplé vody má zákon vlastní pravidla pro poměr základní a spotřební složky, protože byt v rohu domu spotřebuje víc než byt uprostřed.',
    ],
    zdroj: 'zákon č. 67/2013 Sb., § 5 a § 6',
    souvisejici: ['vyuctovani-sluzeb', 'odecet-meridel'],
    clanek: 'vyuctovani-sluzeb',
  },
  {
    slug: 'odecet-meridel',
    pojem: 'Odečet měřidel',
    oblast: 'sluzby',
    definice: 'Zápis stavu vodoměrů, elektroměru, plynoměru a indikátorů topných nákladů k určitému dni.',
    vysvetleni: [
      'Odečet se dělá na konci zúčtovacího období a vždy při předání a vracení bytu. Bez vstupního odečtu je první vyúčtování jen odhad.',
      'Do protokolu patří nejen stav, ale i výrobní číslo měřidla — jinak se nepozná, že bylo mezitím vyměněno.',
    ],
    souvisejici: ['rozuctovani', 'predavaci-protokol', 'odberne-misto'],
    clanek: 'predavaci-protokol',
  },
  {
    slug: 'odberne-misto',
    pojem: 'Odběrné místo (EAN, EIC)',
    oblast: 'sluzby',
    definice: 'Místo dodávky elektřiny nebo plynu označené jednoznačným kódem — EAN u elektřiny, EIC u plynu.',
    vysvetleni: [
      'Kód odběrného místa potřebuješ při každém přepisu na nového nájemce i při změně dodavatele. Je na faktuře i na smlouvě s dodavatelem.',
      'Když je odběrné místo psané přímo na nájemce, řeš přepis ve stejný den jako předání bytu — jinak přijde faktura za energie, které spotřeboval někdo jiný.',
    ],
    souvisejici: ['odecet-meridel', 'predavaci-protokol'],
    clanek: 'predavaci-protokol',
  },
  {
    slug: 'penb',
    pojem: 'PENB',
    oblast: 'sluzby',
    definice: 'Průkaz energetické náročnosti budovy; pronajímatel ho musí předložit zájemci o nájem a předat nájemci.',
    vysvetleni: [
      'Průkaz zpracovává energetický specialista a platí deset let od vyhotovení, pokud se na budově neudělá větší změna dokončené budovy.',
      'Zařazení do třídy A až G říká, jak je budova náročná na energie. U inzerátu se uvádí třída i ukazatele energetické náročnosti.',
    ],
    zdroj: 'zákon č. 406/2000 Sb., o hospodaření energií',
    souvisejici: ['odberne-misto', 'najemni-smlouva'],
  },
  {
    slug: 'svj',
    pojem: 'SVJ',
    oblast: 'sluzby',
    definice: 'Společenství vlastníků jednotek — právnická osoba, která spravuje dům a pozemek za vlastníky bytů.',
    vysvetleni: [
      'Založit se musí v domě, kde je alespoň pět jednotek, z nichž nejméně čtyři patří čtyřem různým vlastníkům.',
      'SVJ předepisuje vlastníkům zálohy na správu a na služby a jednou ročně je vyúčtovává. Pronajímatel pak ze svého vyúčtování od SVJ skládá vyúčtování pro nájemce.',
    ],
    pozor: 'Vyúčtování od SVJ chodí často až na jaře. S vlastním vyúčtováním pro nájemce je proto rozumné počkat na něj, ale pořád stihnout zákonnou čtyřměsíční lhůtu.',
    zdroj: '§ 1194 a § 1198 občanského zákoníku',
    souvisejici: ['fond-oprav', 'vyuctovani-sluzeb'],
  },
  {
    slug: 'fond-oprav',
    pojem: 'Fond oprav',
    oblast: 'sluzby',
    definice: 'Běžné označení pro dlouhodobou zálohu na opravy a správu domu, kterou vlastník jednotky platí společenství.',
    vysvetleni: [
      'Není to zákonný pojem — zákon mluví o příspěvcích na správu domu a pozemku. Na rozdíl od záloh na služby se fond oprav nevyúčtovává proti spotřebě; zůstává v domě na budoucí opravy.',
      'U daní je potřeba rozlišovat: do výdajů patří ta část, která je skutečně nákladem na opravy a správu, ne tvorba rezervy jako taková. Tohle je otázka na účetní.',
    ],
    souvisejici: ['svj', 'zalohy-na-sluzby', 'skutecne-vydaje'],
  },
  {
    slug: 'revize',
    pojem: 'Revize',
    oblast: 'sluzby',
    definice: 'Pravidelná kontrola vyhrazených technických zařízení — elektroinstalace, plynu, komínů, hromosvodu nebo výtahu.',
    vysvetleni: [
      'Lhůty se liší podle zařízení a typu objektu. Za jejich dodržení odpovídá vlastník, i když zařízení užívá nájemce.',
      'Revizní zpráva je doklad, který se hodí nejen pro pojišťovnu, ale i při škodě — bez ní se těžko prokazuje, že zařízení bylo v pořádku.',
    ],
    souvisejici: ['penb', 'pojisteni-nemovitosti'],
  },
  {
    slug: 'pojisteni-nemovitosti',
    pojem: 'Pojištění pronajímané nemovitosti',
    oblast: 'sluzby',
    definice: 'Pojištění stavby, případně domácnosti a odpovědnosti; u pronajímaného bytu je potřeba pojistku na pronájem výslovně sjednat.',
    vysvetleni: [
      'Pojištění stavby kryje samotnou budovu, pojištění domácnosti vybavení. Nájemce si vlastní věci pojišťuje sám — pojistka pronajímatele na ně nedosáhne.',
      'Roční pojistné je při uplatnění skutečných výdajů daňově uznatelný náklad. Vedle pojištění stavby stojí za zvážení i pojištění odpovědnosti — kryje škodu, kterou způsobíš sousedům, typicky vytopení z prasklé stoupačky.',
    ],
    pozor: 'Mnoho pojistek domácnosti neplatí, pokud byt pronajímáš a pojišťovně jsi to neoznámil. Vyplatí se to ověřit dřív, než nastane škoda.',
    souvisejici: ['revize', 'skutecne-vydaje'],
  },
]
